### ISSUE TITLE
error on install ./pygluu-compose.pyz up

### ISSUE THREAD

**Issue by karma2max** [GluuFederation/community-edition-containers#20]
./pygluu-compose.pyz up
[I] Attempting to gather external IP address
[I] Using 192.168.0.3 as external IP address
Creating consul ... done
Creating vault  ... done
[I] Checking Vault status
[W] Unable to get seal status in Vault; retrying ...
[W] Unable to get seal status in Vault; retrying ...
[W] Unable to get seal status in Vault; retrying ...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./pygluu-compose.pyz/__main__.py", line 3, in <module>
  File "./pygluu-compose.pyz/_bootstrap/__init__.py", line 193, in bootstrap
  File "./pygluu-compose.pyz/_bootstrap/__init__.py", line 33, in run
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/pygluu/compose/cli.py", line 59, in up
    app.up()
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/pygluu/compose/app.py", line 493, in up
    self.prepare_config_secret()
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/pygluu/compose/app.py", line 409, in prepare_config_secret
    secret.setup()
  File "/root/.shiv/pygluu-compose_6645e3bbb576cf0a9854dc1898929d7262bd7bd78d70c1f4baa04361478825d8/site-packages/pygluu/compose/app.py", line 140, in setup
    if not status["initialized"]:
KeyError: 'initialized'

**Comment by karma2max** [comment]
on Vault Container: 

WARNING! Unable to read storage migration status.
2020-09-10T07:07:40.999Z [WARN]  storage migration check error: error="Get http://consul:8500/v1/kv/vault/core/migration: dial tcp 172.26.0.2:8500: connect: no route to host"
2020-09-10T07:07:44.007Z [WARN]  storage migration check error: error="Get http://consul:8500/v1/kv/vault/core/migration: dial tcp 172.26.0.2:8500: connect: no route to host"
2020-09-10T07:07:47.015Z [WARN]  storage migration check error: error="Get http://consul:8500/v1/kv/vault/core/migration: dial tcp 172.26.0.2:8500: connect: no route to host"

**Comment by iromli** [comment]
@karma2max can you open the ticket at https://support.gluu.org, please? This GitHub issue tracker is for development ticket. Thanks.

**Comment by iromli** [comment]
Closing stale issue
