### ISSUE TITLE
README Process for single host startup fails

### ISSUE THREAD

**Issue by shairozan** [GluuFederation/community-edition-containers#24]
I followed the readme process for initializing a project (single-host) for example:

```
pygluu-compose/examples/single-host on  master via 💠 default on ☁️  (us-east-1) on ☁️ darrell.breeden@cumulose.com
✦ ❯ ls
couchbase.crt		      docker-compose.yml  jackrabbit_admin_password  svc.cr_rotate.yml	 svc.ldap.yml	     svc.oxpassport.yml    svc.radius.yml  svc.vault_autounseal.yml  vault_secret_id.txt
couchbase_password	      gcp_kms_creds.json  job.persistence.yml	     svc.fido2.yml	 svc.oxauth.yml      svc.oxshibboleth.yml  svc.redis.yml   vault_gluu_policy.hcl     volumes
couchbase_superuser_password  gcp_kms_stanza.hcl  svc.casa.yml		     svc.jackrabbit.yml  svc.oxd_server.yml  svc.oxtrust.yml	   svc.scim.yml    vault_role_id.txt

✦ ❯
```

```
✦ ❯ pygluu-compose up
[I] Attempting to gather external IP address
[I] Using 192.168.0.23 as external IP address
Creating consul ... done
Creating vault  ... done
[I] Checking Vault status
[W] Unable to get seal status in Vault; retrying ...
[W] Unable to get seal status in Vault; retrying ...
[W] Unable to get seal status in Vault; retrying ...
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dbreeden/bin/pygluu-compose/__main__.py", line 3, in <module>
  File "/Users/dbreeden/bin/pygluu-compose/_bootstrap/__init__.py", line 241, in bootstrap
  File "/Users/dbreeden/bin/pygluu-compose/_bootstrap/__init__.py", line 36, in run
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/pygluu/compose/cli.py", line 74, in up
    app.up()
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/pygluu/compose/app.py", line 498, in up
    self.prepare_config_secret()
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/pygluu/compose/app.py", line 414, in prepare_config_secret
    secret.setup()
  File "/Users/dbreeden/.shiv/pygluu-compose_6b74d073e249ccce2f7513168ef6212105092b8cddc7f645d9a946375d28e85a/site-packages/pygluu/compose/app.py", line 147, in setup
    if not status["initialized"]:
KeyError: 'initialized'
```

**Comment by iromli** [comment]
Hi @shairozan, please open a ticket at https://support.gluu.org.
Thanks.
